services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-rastreo-app
    links:
      - redis-server
    ports:
      - "8080:8080"

  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"

